### ISSUE TITLE
createFundedAddress() can result in loss of actor's BTC

### ISSUE THREAD

**Issue by dexX7** [msgilligan/bitcoin-spock#35]
Step 1) actorA is funded with 1.0 BTC via createFundedAddress()
Step 2) actorB is funded with 1.0 BTC via createFundedAddress()

In the worst the coins of A are used to "sendToAddress" of B.

How the coin selection choses the coins to send is pretty much out of scope, and I don't see a straight forward guard against this behavior.

There is the RPC call "lockunspent" which could be used to "freeze" balances during funding and transfer periods..

**Comment by msgilligan** [comment]
We could use bitcoinj to create wallets and addresses for which Core won't have the private key, but maybe there is a simpler solution.

**Comment by dexX7** [comment]
Hmm.. I'd prefer to avoid the inclusion of BitcoinJ as far as possible, because it adds dependencies and a certain black box risk, and especially the appearingly random delay of results worries me - using `Thread.sleep(400)` can work, but it might not work in all situations. Very high values on the other hand would delay the execution significantly.

**Comment by dexX7** [comment]
Here is an idea which I'm probably going to test later:

1) Lock unspent outputs per default with RPC "lockunspent" in "createFundedAddress".
2) When using "sendBitcoin", the outputs are unlocked and locked again once finished.

I *hope* RPC "lockunspent" only affects RPC "listunspent" and does not really lock outputs on a low level, so it would only have an impact on "sendBitcoin" - which we fully control.

**Comment by msgilligan** [comment]
The `Thread.sleep(400)` is a hack, and there's probably a better way (callback) to handle that. I agree, though that there is probably a better solution.

**Comment by msgilligan** [comment]
Would it be possible to find the UTXOs of the coinbase transactions from RegTest "mining" and use raw transactions rather than `sendAddress()` to fund the "step" and "funded" addresses?

Note that we could also put the test addresses in to named account which might make it easier telling them apart (but we still wouldn't rely on named accounts to stop Core from using them in transactions.)

Another thing we could do to simplify setup is create a global "funded address" for the tests and create a `generateBlock()` method for tests that always sends newly unlocked coins to that global funded address.

**Comment by dexX7** [comment]
Great ideas!

> global "funded address" ... always sends newly unlocked coins to that global funded address

Are you referring to a test-global funded address, similar to the "faucetAddress" in the MoneyManSpec or something with a greater scope?

If mined coins are used for funding, we can get rid of "sendtoaddresss" and cut all ties to the account system.
