### ISSUE TITLE
Incompatible with Bitcoin Core 0.10

### ISSUE THREAD

**Issue by dexX7** [msgilligan/bitcoin-spock#44]
We need to overthink funding and other methods once again, I believe. There are two points I noticed already:

1) `setgenerate` returns no longer `null`, but a list of block hashes. This is an easy fix.

2) Assuming we start fresh and generate a block with `setgenerate true 1`, and then using `getnewaddress`, then the address is returned that received the generated coins. When `getnewaddress` is used before generating a block, then it looks like it's another address.

**Comment by msgilligan** [comment]
We should try (if it's not too hard or clunky) to implement the RPC client code so that it works with multiple versions of Bitcoin/Omni Core and gracefully degrades on the older versions. The same is probably true for the test support libraries as well.

For the tests themselves, the issue may be more complicated. You may have noticed that I created a tag `mastercore-0.0.8` because there were some tests that work with 0.0.8 that didn't work with 0.0.9 and vice versa. Perhaps we could user the Spock `@IgnoreIf` or `@Requires` annotation to enable or disable tests for specific versions (See [extensions.html](http://spock-framework.readthedocs.org/en/latest/extensions.html)). If that becomes unwieldy we could create branches for older versions and keep the latest on `master` .

**Comment by dexX7** [comment]
Using extensions sounds great. Keeping a branch for each new version bears the risk that tests, which should be used by old and new may end up being just added to the new branch.

I'm surpirsed of the new behavior of `getnewaddress`. While `setgenerate` is easy to handle in both versions, I have to figure out how the address management of Bitcoin Core actually works internally.

**Comment by dexX7** [comment]
Regarding 1: we could simply ignore any result, or return an `Object` which should work with 0.9's empty results as well as a list of block hashes. What do you prefer?

Regarding 2: still not solved. :/

**Comment by dexX7** [comment]
Oh well, this is odd. All tests pass with the Bitcoin Core 0.10 build. Looks like there was a change regarding `getnewaddress` ... or did we change anything I missed?

**Comment by msgilligan** [comment]
I don't know of any changes that were intended to solve that issue, but you made a lot of changes to address creation/funding so maybe one of those did it?
